vue/tsconfig: add esnext to lib
ERROR in /home/t/work/cv/lib/data/raw.ts
../lib/data/raw.ts
[tsl] ERROR in /home/t/work/cv/lib/data/raw.ts(31,10)
      TS2339: Property 'flat' does not exist on type 'ActorLanguage[][]'.