This breaks raw loader
@ ./src/Charts.tsx 4:0-60 14:43-56 27:27-40 28:28-42
 @ ./src/App.tsx 8:0-34 99:39-45
 @ ./src/entry.tsx 3:0-24 8:48-51

ERROR in ./src/constants.ts 27:6-47
[tsl] ERROR in ~/cv/packages/react/src/constants.ts(27,7)
      TS6059: File '~/cv/packages/chart-react-victory/src/charts.tsx' is not under 'rootDir' '~/cv/packages/lib'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via "@tony/cv-chart-react-victory/src/charts" from file '~/cv/packages/react/src/constants.ts' with packageId '@tony/cv-chart-react-victory/src/charts.tsx@0.0.1'
    Imported via "@tony/cv-chart-react-victory/src/charts" from file '~/cv/packages/react/src/constants.ts' with packageId '@tony/cv-chart-react-victory/src/charts.tsx@0.0.1'
    Root file specified for compilation
 @ ./src/Charts.tsx 4:0-60 14:43-56 27:27-40 28:28-42
 @ ./src/App.tsx 8:0-34 99:39-45
 @ ./src/entry.tsx 3:0-24 8:48-51

ERROR in ./src/constants.ts 33:6-43
[tsl] ERROR in ~/cv/packages/react/src/constants.ts(33,7)
      TS6059: File '~/cv/packages/chart-react-vis/src/charts.tsx' is not under 'rootDir' '~/cv/packages/lib'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via "@tony/cv-chart-react-vis/src/charts" from file '~/cv/packages/react/src/constants.ts' with packageId '@tony/cv-chart-react-vis/src/charts.tsx@0.0.1'
    Imported via "@tony/cv-chart-react-vis/src/charts" from file '~/cv/packages/react/src/constants.ts' with packageId '@tony/cv-chart-react-vis/src/charts.tsx@0.0.1'
    Root file specified for compilation
 @ ./src/Charts.tsx 4:0-60 14:43-56 27:27-40 28:28-42
 @ ./src/App.tsx 8:0-34 99:39-45
 @ ./src/entry.tsx 3:0-24 8:48-51

ERROR in ./src/constants.ts 39:6-44
[tsl] ERROR in ~/cv/packages/react/src/constants.ts(39,7)
      TS6059: File '~/cv/packages/chart-react-nivo/src/charts.tsx' is not under 'rootDir' '~/cv/packages/lib'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via "@tony/cv-chart-react-nivo/src/charts" from file '~/cv/packages/react/src/constants.ts' with packageId '@tony/cv-chart-react-nivo/src/charts.tsx@0.0.1'
    Imported via "@tony/cv-chart-react-nivo/src/charts" from file '~/cv/packages/react/src/constants.ts' with packageId '@tony/cv-chart-react-nivo/src/charts.tsx@0.0.1'
    Root file specified for compilation
 @ ./src/Charts.tsx 4:0-60 14:43-56 27:27-40 28:28-42
 @ ./src/App.tsx 8:0-34 99:39-45
 @ ./src/entry.tsx 3:0-24 8:48-51

ERROR in ../ui-range-slider/index.ts 1:28-38
[tsl] ERROR in ~/cv/packages/ui-range-slider/index.ts(1,29)
      TS6059: File '~/cv/packages/ui-range-slider/slider.ts' is not under 'rootDir' '~/cv/packages/lib'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via "./slider" from file '~/cv/packages/ui-range-slider/index.ts'
    Imported via "./slider" from file '~/cv/packages/ui-range-slider/index.ts'
    Root file specified for compilation
 @ ./src/Settings/FilterDateRange.tsx 3:0-34
 @ ./src/Settings/index.tsx 2:0-52 53:95-110
 @ ./src/App.tsx 7:0-63 95:95-118 97:114-122
 @ ./src/entry.tsx 3:0-24 8:48-51

ERROR in ../ui-range-slider/slider.ts 5:18-75
[tsl] ERROR in ~/cv/packages/ui-range-slider/slider.ts(5,19)
      TS2307: Cannot find module '!!raw-loader!sass-loader!nouislider/dist/nouislider.css' or its corresponding type declarations.
 @ ../ui-range-slider/index.ts 1:0-39 1:0-39
 @ ./src/Settings/FilterDateRange.tsx 3:0-34
 @ ./src/Settings/index.tsx 2:0-52 53:95-110
 @ ./src/App.tsx 7:0-63 95:95-118 97:114-122
 @ ./src/entry.tsx 3:0-24 8:48-51

ERROR in ../ui-switch/index.ts 1:25-37
[tsl] ERROR in ~/cv/packages/ui-switch/index.ts(1,26)
      TS6059: File '~/cv/packages/ui-switch/switcher.ts' is not under 'rootDir' '~/cv/packages/lib'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via "./switcher" from file '~/cv/packages/ui-switch/index.ts'
    Imported via "./switcher" from file '~/cv/packages/ui-switch/index.ts'
    Root file specified for compilation
 @ ./src/Settings/FilterToggles.tsx 3:0-28
 @ ./src/Settings/index.tsx 4:0-48 55:39-52
 @ ./src/App.tsx 7:0-63 95:95-118 97:114-122
 @ ./src/entry.tsx 3:0-24 8:48-51

ERROR in ../ui-switch/switcher.ts 6:18-87
[tsl] ERROR in ~/cv/packages/ui-switch/switcher.ts(6,19)
      TS2307: Cannot find module '!!raw-loader!sass-loader!a-simple-switch/src/sass/SimpleSwitch.scss' or its corresponding type declarations.
 @ ../ui-switch/index.ts 1:0-38 1:0-38
 @ ./src/Settings/FilterToggles.tsx 3:0-28
 @ ./src/Settings/index.tsx 4:0-48 55:39-52
 @ ./src/App.tsx 7:0-63 95:95-118 97:114-122
 @ ./src/entry.tsx 3:0-24 8:48-51

37 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.71.0 compiled with 37 errors in 2994 ms