build(deps): Temporarily downgrade carbon (1.6.x -> 1.7.x)
[vite]: Rollup failed to resolve import "dom-to-image-more" from "/home/runner/work/cv/cv/node_modules/@carbon/charts/services/essentials/dom-utils.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "dom-to-image-more" from "/home/runner/work/cv/cv/node_modules/@carbon/charts/services/essentials/dom-utils.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/runner/work/cv/cv/node_modules/vite/dist/node/chunks/dep-24daf00c.js:46525:23)
    at onwarn (/home/runner/work/cv/cv/node_modules/@vitejs/plugin-react/dist/index.cjs:257:9)
    at onRollupWarning (file:///home/runner/work/cv/cv/node_modules/vite/dist/node/chunks/dep-24daf00c.js:46546:9)
    at onwarn (file:///home/runner/work/cv/cv/node_modules/vite/dist/node/chunks/dep-24daf00c.js:46296:13)
    at Object.onwarn (file:///home/runner/work/cv/cv/node_modules/rollup/dist/es/shared/node-entry.js:25166:13)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/cv/cv/node_modules/rollup/dist/es/shared/node-entry.js:23801:26)
    at file:///home/runner/work/cv/cv/node_modules/rollup/dist/es/shared/node-entry.js:23761:26